[package]
name = "soaaos"
version = "0.1.0"
edition = "2024"

[dependencies]
quote = "1.0.37"
rand = "0.9.0"
syn = { version = "2.0.90", features = ["full", "extra-traits"] }

[lib]
proc-macro = true

[dev-dependencies]
insta = "1.42.2"
